language: ruby
cache: bundler

rvm:
 - 2.3.0

script:
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rake db:migrate --trace
 - bundle exec rspec -fd spec/

before_script:
  - mysql -e 'create database my_app_test'
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs